# Engine configure switches for the neutral Online source image. This mirrors
# CPLinux-LOKit, with the shared neutral configuration included below.
INCLUDE:OnlineLinuxCommon
INCLUDE:Langs

--enable-noto-font
--enable-sal-log
--enable-epm
--with-package-format=deb rpm
--with-myspell-dicts
--with-external-dict-dir=/usr/share/hunspell
--with-external-hyph-dir=/usr/share/hyphen
--with-external-thes-dir=/usr/share/mythes

--without-gssapi

--enable-python=internal
--without-system-curl
--without-system-expat
--without-system-fontconfig
--without-system-freetype
--without-system-graphite
--without-system-harfbuzz
--without-system-icu
--without-system-jars
--without-system-libpng
--without-system-libxml
